export type RightPanelStyle = Partial<CSSStyleDeclaration>;

export const RIGHT_PANEL_DARK_STYLES = {
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    boxSizing: "border-box",
    padding: "16px",
    width: "100%",
    minHeight: "100%",
    height: "100%",
    overflowY: "auto",
    backgroundColor: "#1e293b",
    color: "#f1f5f9",
    border: "1px solid #334155",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.4)",
    fontSize: "13px",
    lineHeight: "1.5",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  heading: {
    margin: "0",
    color: "#f8fafc",
    fontSize: "16px",
    fontWeight: "600",
  },
  description: {
    margin: "0",
    color: "#94a3b8",
    fontSize: "12px",
    lineHeight: "1.4",
  },
  text: {
    color: "#cbd5e1",
    fontSize: "13px",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  formRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    width: "100%",
    boxSizing: "border-box",
  },
  status: {
    color: "#94a3b8",
    fontSize: "12px",
    overflowWrap: "break-word",
  },
  label: {
    display: "block",
    marginBottom: "4px",
    color: "#cbd5e1",
    fontSize: "12px",
    fontWeight: "500",
  },
  input: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "36px",
    padding: "8px 10px",
    border: "1px solid #475569",
    borderRadius: "4px",
    outline: "none",
    backgroundColor: "#0f172a",
    color: "#f8fafc",
    fontSize: "14px",
    fontFamily: "inherit",
  },
  expression: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "96px",
    padding: "8px 10px",
    border: "1px solid #475569",
    borderRadius: "4px",
    backgroundColor: "#0f172a",
    color: "#f8fafc",
    fontFamily: "monospace",
    resize: "vertical",
  },
  methodSelect: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "36px",
    padding: "8px 10px",
    border: "1px solid #475569",
    borderRadius: "4px",
    outline: "none",
    backgroundColor: "#0f172a",
    color: "#f8fafc",
    fontSize: "14px",
    fontFamily: "inherit",
  },
  range: {
    width: "100%",
    accentColor: "#3b82f6",
    flex: "1 1 auto",
    minWidth: "0",
  },
  checkbox: {
    width: "16px",
    height: "16px",
    accentColor: "#3b82f6",
    cursor: "pointer",
  },
  radio: {
    accentColor: "#3b82f6",
    cursor: "pointer",
  },
  output: {
    color: "#f8fafc",
    fontWeight: "600",
  },
  selectOption: {
    backgroundColor: "#0f172a",
    color: "#f8fafc",
  },
  button: {
    boxSizing: "border-box",
    minHeight: "36px",
    padding: "8px 14px",
    border: "1px solid #475569",
    borderRadius: "4px",
    backgroundColor: "#334155",
    color: "#f8fafc",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
  },
  operationButton: {
    boxSizing: "border-box",
    minHeight: "36px",
    padding: "8px 14px",
    border: "1px solid #2563eb",
    borderRadius: "4px",
    backgroundColor: "#3b82f6",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    textAlign: "center",
  },
  downloadButton: {
    boxSizing: "border-box",
    minHeight: "36px",
    padding: "8px 14px",
    border: "1px solid #2563eb",
    borderRadius: "4px",
    backgroundColor: "#3b82f6",
    color: "#ffffff",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    textAlign: "center",
  },
  layerList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  layerCard: {
    boxSizing: "border-box",
    padding: "8px 12px",
    border: "1px solid #334155",
    borderRadius: "4px",
    backgroundColor: "#0f172a",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.2)",
  },
  checkLabel: {
    overflow: "hidden",
    color: "#f1f5f9",
    fontSize: "12px",
    fontWeight: "500",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    cursor: "pointer",
    userSelect: "none",
  },
  layerSubform: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "8px",
    paddingTop: "8px",
    borderTop: "1px solid #334155",
  },
  wdSliderControl: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
    width: "100%",
    boxSizing: "border-box",
  },
  wdNumberInput: {
    boxSizing: "border-box",
    width: "82px",
    minWidth: "82px",
    maxWidth: "82px",
    minHeight: "36px",
    padding: "6px 8px",
    border: "1px solid #475569",
    borderRadius: "4px",
    outline: "none",
    backgroundColor: "#0f172a",
    color: "#f8fafc",
    fontSize: "13px",
    textAlign: "right",
    flex: "0 0 82px",
  },
  wdStatsGrid: { 
    display: "grid", 
    gridTemplateColumns: "1fr 1fr", 
    gap: "6px" 
  },
  wdStatItem: { 
    padding: "8px", 
    border: "1px solid #334155", 
    borderRadius: "4px", 
    backgroundColor: "#0f172a" 
  },
  wdStatLabel: { 
    display: "block", 
    color: "#94a3b8", 
    fontSize: "11px" 
  },
  wdStatValue: { 
    display: "block", 
    color: "#f8fafc", 
    fontSize: "14px", 
    fontWeight: "600" 
  },
  wdProgress: { 
    padding: "8px", 
    backgroundColor: "#1e3a8a", 
    color: "#93c5fd", 
    fontSize: "12px" 
  },
  wdBadge: { 
    display: "inline-block", 
    padding: "3px 8px", 
    borderRadius: "999px", 
    backgroundColor: "#334155", 
    color: "#cbd5e1", 
    fontSize: "11px", 
    fontWeight: "600" 
  },
  wdBadgeOk: { 
    backgroundColor: "#14532d", 
    color: "#86efac" 
  },
  wdBadgeError: { 
    backgroundColor: "#7f1d1d", 
    color: "#fca5a5" 
  },
  wdBadgeRunning: { 
    backgroundColor: "#1e3a8a", 
    color: "#93c5fd" 
  },
  rasterList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  rasterRow: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "10px",
    backgroundColor: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "4px",
  },
  rasterControls: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  rasterBands: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  operations: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    padding: "8px",
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "4px",
  },
  operationsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "6px",
    padding: "8px",
    backgroundColor: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "4px",
  },
  operationRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  countGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  mceRows: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  mceRow: {
    display: "grid",
    gap: "6px",
    padding: "10px",
    backgroundColor: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "4px",
  },
  mceWeightInput: {
    boxSizing: "border-box",
    minHeight: "36px",
    padding: "8px 10px",
    color: "#f8fafc",
    backgroundColor: "#0f172a",
    border: "1px solid #475569",
    borderRadius: "4px",
    font: "inherit",
  },
  ahpLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#cbd5e1",
    fontWeight: "500",
  },
  ahpContainer: {
    flexDirection: "column",
    gap: "8px",
    overflowX: "auto",
  },
  ahpInput: {
    boxSizing: "border-box",
    width: "72px",
    minHeight: "32px",
    padding: "6px",
    color: "#f8fafc",
    backgroundColor: "#0f172a",
    border: "1px solid #475569",
    borderRadius: "4px",
    font: "inherit",
  },
  ahpField: {
    boxSizing: "border-box",
    width: "72px",
    minHeight: "32px",
    padding: "6px",
    color: "#f8fafc",
    backgroundColor: "#0f172a",
    border: "1px solid #475569",
    borderRadius: "4px",
    font: "inherit",
  },
  ahpInputDisabled: {
    backgroundColor: "#334155",
    color: "#64748b",
    borderColor: "#475569",
    cursor: "not-allowed",
  },
  ahpButton: {
    alignSelf: "flex-start",
  },
  table: {
    borderCollapse: "collapse",
    width: "100%",
  },
  tableRow: {
    borderBottom: "1px solid #334155",
  },
  tableHeader: {
    padding: "6px",
    color: "#cbd5e1",
    fontWeight: "600",
    textAlign: "left",
  },
  tableCell: {
    padding: "6px",
    color: "#cbd5e1",
  },
  fieldset: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    margin: "0",
    padding: "10px",
    border: "1px solid #334155",
    borderRadius: "4px",
  },
  legend: {
    padding: "0 4px",
    color: "#cbd5e1",
    fontWeight: "600",
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#cbd5e1",
  },
  averagingGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  flexCol:{
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    marginTop: "15px",
  },
  flexRow:{
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  inputDescription:{
    color: "#94a3b8",
    fontSize: "11px",
    lineHeight: "1.4",
  },
  section:{
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  hidden: { display: "none" },
  visibleFlex: { display: "flex" },
  visibleGrid: { display: "grid" },
  fileField: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "36px",
    padding: "6px 10px",
    border: "1px solid #475569",
    borderRadius: "4px",
    outline: "none",
    backgroundColor: "#0f172a",
    color: "#f8fafc",
    fontSize: "13px",
    fontFamily: "inherit",
  },
  calculatorButton: {
    boxSizing: "border-box",
    minHeight: "32px",
    padding: "6px 10px",
    border: "1px solid #475569",
    borderRadius: "4px",
    backgroundColor: "#334155",
    color: "#f8fafc",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500",
  },
  statusError: {
    color: "#f87171",
    fontSize: "12px",
    overflowWrap: "break-word",
  },
  downloads: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
  },
} as const;

export const STYLE_CLASS_ALIASES = {
  panel: ["geolibre-plugin-right-panel", "spazio-container"],
  heading: "spazio-title",
  description: "spazio-description",
  text: "spazio-text",
  formContainer: "spazio-form-container",
  formRow: "spazio-form-row",
  status: "spazio-status",
  label: "spazio-input-label",
  input: "spazio-text-field",
  inputDescription: "spazio-input-description",
  expression: "spazio-expression-field",
  methodSelect: "spazio-dropdown",
  range: "spazio-slider",
  checkbox: "spazio-checkbox",
  radio: "spazio-radio",
  output: "spazio-output",
  selectOption: "spazio-dropdown-options",
  button: "spazio-button",
  operationButton: "spazio-submit-button",
  downloadButton: "spazio-submit-button",
  layerList: "spazio-layer-list",
  layerCard: "spazio-layer-card",
  checkLabel: "spazio-check-label",
  layerSubform: "spazio-layer-subform",
  wdSliderControl: "spazio-wd-slider-control",
  wdNumberInput: "spazio-wd-number-input",
  wdStatsGrid: "spazio-wd-stats-grid",
  wdStatItem: "spazio-wd-stat-item",
  wdStatLabel: "spazio-wd-stat-label",
  wdStatValue: "spazio-wd-stat-value",
  wdProgress: "spazio-wd-progress",
  wdBadge: "spazio-wd-badge",
  wdBadgeOk: "spazio-wd-badge-ok",
  wdBadgeError: "spazio-wd-badge-error",
  wdBadgeRunning: "spazio-wd-badge-running",
  rasterList: "spazio-raster-list",
  rasterRow: "spazio-raster-row",
  rasterControls: "spazio-raster-controls",
  rasterBands: "spazio-raster-bands",
  operations: "spazio-operations",
  operationsGrid: "spazio-operations-grid",
  operationRow: "spazio-operation-row",
  countGroup: "spazio-count-group",
  mceRows: "spazio-mce-rows",
  mceRow: "spazio-mce-row",
  mceWeightInput: "spazio-mce-weight-input",
  ahpLabel: "spazio-ahp-label",
  ahpContainer: "spazio-ahp-container",
  ahpInput: "spazio-ahp-input",
  ahpInputDisabled: "spazio-ahp-input-disabled",
  ahpButton: "spazio-ahp-button",
  table: "spazio-ahp-table",
  tableRow: "spazio-ahp-table-row",
  tableHeader: "spazio-ahp-headers",
  tableCell: "spazio-ahp-cell",
  fieldset: "spazio-fieldset",
  legend: "spazio-legend",
  radioLabel: "spazio-radio-label",
  averagingGroup: "spazio-averaging-group",
  hidden: "spazio-hidden",
  visibleFlex: "spazio-visible-flex",
  visibleGrid: "spazio-visible-grid",
  flexCol: "spazio-flex-col",
  flexRow: "spazio-flex-row",
  section: "spazio-section",
  fileField: "spazio-file-field",
  calculatorButton: "spazio-calculator-button",
  statusError: "spazio-status-error",
  downloads: "spazio-downloads",
  ahpField: ["spazio-ahp-field", "spazio-ahp-input"],
} as const;

export type RightPanelDarkStyleName = keyof typeof RIGHT_PANEL_DARK_STYLES;

export function applyRightPanelDarkStyle(
  element: HTMLElement,
  styleName: RightPanelDarkStyleName,
): void {
  const styles = RIGHT_PANEL_DARK_STYLES[styleName];
  const alias = STYLE_CLASS_ALIASES[styleName];
  const classNames = Array.isArray(alias) ? alias : [alias ?? `spazio-${String(styleName).replace(/[A-Z]/g, (match) => `-${match.toLowerCase()}`)}`];
  for (const className of classNames) {
    if (className) element.classList.add(className);
  }
  Object.assign(element.style, styles);
}
